from typing import Any


def export(*args: Any, **kwargs: Any) -> Any: ...
def export_testcase(*args: Any, **kwargs: Any) -> Any: ...
def is_large_tensor(*args: Any, **kwargs: Any) -> Any: ...
def annotate(*args: Any, **kwargs: Any) -> Any: ...
def apply_annotation(*args: Any, **kwargs: Any) -> Any: ...
def scoped_anchor(*args: Any, **kwargs: Any) -> Any: ...
def as_output(*args: Any, **kwargs: Any) -> Any: ...
def grad(*args: Any, **kwargs: Any) -> Any: ...
def load_model(*args: Any, **kwargs: Any) -> Any: ...


LARGE_TENSOR_DATA_THRESHOLD: int
available: bool
