configs {
  key: "pytorch-pfn-extras"
  value {
    requirement {
      cpu: 2
      gpu: 2
      memory: 16
      disk: 10
    }
    time_limit: {
      seconds: 1200
    }
    command: "bash .flexci/run.sh"
  }
}
