from pytorch_pfn_extras.cuda._allocator import stream
from pytorch_pfn_extras.cuda._allocator import use_torch_mempool_in_cupy
from pytorch_pfn_extras.cuda._allocator import use_default_mempool_in_cupy
