name: "Test CPU"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install
      run: |
        pip install -U pip wheel
        pip install 'torch==1.9.*'
        pip install 'torchvision==0.10.*'
        pip install pytest
        pip install matplotlib tensorboard ipython ipywidgets pandas optuna onnx onnxruntime pytorch-ignite
        pip install -v -e .
        # Test PPE is importable with minimum dependency
        python -c 'import pytorch_pfn_extras'

    - name: Test CPU only
      run: |
        pytest -m "not gpu" tests
